# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oHaWQT2Ike7hzyvlB6gv62hzqLCGNWX3
"""

#Q1
C = 'y'
while C == 'y':
    marks = float(input("Enter your marks: "))
    if marks < 25:
        print("Your grade is F.")
    elif (marks >= 25) & (marks < 45):
        print("Your grade is E.")
    elif (marks >= 45) & (marks < 50):
        print("Your grade is D.")
    elif (marks >= 50) & (marks < 60):
        print("Your grade is C.")
    elif (marks >= 60) & (marks < 80):
        print("Your grade is B.")
    elif (marks >= 80) & (marks <= 100):
        print("Your grade is A.")
    else:
        print("Invalid Input (Marks should be less than or equal to 100.)")
    
    C = input("Do you want to continue? (Enter y for yes and n (or any key other than y) for no)")

#Q2
C = 'y'
while C == 'y':
    year = int(input("Enter a year: "))
    if year % 4 == 0:
        if (year % 100 == 0) & (year % 400 == 0):
            print(f"{year} is a leap year.")
        elif (year % 100 == 0) & (year % 400 != 0):
            print(f"{year} is not a leap year.")
        else:
            print(f"{year} is a leap year.")
    else:
        print(f"{year} is not a leap year.")
    C = input("Do you want to continue? (Enter y for yes and n (or any key other than y) for no)")

#Q3
import random
print("MULTIPLICATION GAME FOR KIDS [Solve 10 randomly generated questions] :)")
a = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

C = 'y'
while C == 'y':
    i = 1
    while i <= 10:
        num1 = random.choice(a)
        num2 = random.choice(a)
        answer = int(input(f"Question {i}: {num1} x {num2} = "))
        if answer == (num1 * num2):
            print("Right!")
        else:
            print(f"Wrong. The answer is {num1 * num2}.")
        i += 1
    C = input("Do you want to play again? [Press 'y' for yes and any other key to exit.]")

#Q4
print('''Program to determine no. of candies in the bowl given that:\n
1. On dividing candies evenly among 5 people, the amount leftover is 2.
2. On dividing candies evenly among 6 people, the amount leftover is 3.
3. On dividing candies evenly among 7 people, the amount leftover is 2.\n\n''')

for candies in range(0, 200):
    if ((candies % 5) == 2) & ((candies % 6) == 3) & ((candies % 7) == 2):
        print(f"Number of candies in the jar is {candies}.")