# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QscgcJL3dM-RtNuNBskYQpcWTIwtQ0_o
"""

# Q1
given_string = "Python is a case sensitive language"
print(len(given_string))
print(given_string[::-1])
new_string = given_string[10:26]
print(new_string)
print(given_string.replace('a case sensitive', 'object oriented'))
print(given_string.find("a"))
print(given_string.replace(' ', ''))


# Q2
Name = input("Enter your name: ")
SID = input("Enter your SID: ")
Dep_name = input("Enter your department name: ")
CGPA = input("Enter your CGPA: ")
print("Hey,", Name, "Here!")
print("My SID is", SID)
print("I am from", Dep_name, "department and my CGPA is", CGPA)

# Q3
a = 56
b = 10
print("a&b=", a & b)
print("a|b=", a | b)
print("a^b", a ^ b)
print("a << 2 : ", a << 2, " and b << 2: ", b << 2)
print("a >> 2 :", a >> 2, " and b >> 4:", b >> 4)


# q4
input_sent = input("Enter a sentence:")
if "name" in input_sent:
    print("Yes")

else:
    print("No")

# Q5
side_1 = int(input("Enter the side 1: "))
side_2 = int(input("Enter the side 2: "))
side_3 = int(input("Enter the side 3: "))

a = side_1 + side_2
b = side_2 + side_3
c = side_3 + side_1

x = (side_1 < b)
y = (side_2 < c)
z = (side_3 < a)

answer = str(x & y & z)
answer = answer.replace("True", "Yes")
answer = answer.replace("False", "No")

print(answer)

# Q6

#obtaining user input
a=int(input("Enter first number."))
b=int(input("Enter second number."))

#using binary XOR operation and then conversion to string
c=str(bin(a^b))

print(c.count("1"))